# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Vijaykumar Bhattacharji
tagline:             'Personal Blog'
description:         'My Personal blog where I update what I did everyday. It will act as my daily diary'
url:                 http://vijaykumarbhattacharji.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Vijaykumar
  email:             falconandeagle@live.com

# Custom vars
version:             1.0.0
